### PR TITLE
Updated S1155/S1255 data from S1155+ECS (pump fw version 2.23.4)

### PR DESCRIPTION
**Pull request by geekuality**
Updated registers with missing ECS ("climate system 2") data (that is still not listed in any Nibe documentation that I could find, I originally got them by asking Nibe's Finnish service department via email).

CSV generated by the pump: [modbus_addresses_all_20240119-06544323025004-1.csv](https://github.com/yozik04/nibe/files/13989485/modbus_addresses_all_20240119-06544323025004-1.csv)

### CODE REVIEW

**Comment by geekuality** [comment]
I wasn't quite sure how to handle registers that had different address in the source CSV vs my file directly from the pump. Decided to merge all changes and additions, so several unnamed registers' (`id:xxxx`) addresses were updated in CSV and in addition five named registers were changed in CSV and also changed the JSON. 🤷‍♀️ 

An example of changed address: https://github.com/yozik04/nibe/pull/147/files#diff-9d9d8a95e5230942a723af84ba4c7ad95225c95d9a25f88987160fe168a1d962L912-R925

**Comment by yozik04** [comment]
Did you generate JSON or you have manually edited?

**Comment by geekuality** [comment]
Generated. (While I was at it, I am just finishing another PR for improvements in extensions and the generation script. 😄 )

**Comment by yozik04** [comment]
Do you want me to merge this one or there will be improvements?

**Comment by geekuality** [comment]
Oh, this one is fine by me. :)

**Comment by geekuality** [comment]
... As in, go ahead with merge. 😆

**Comment by yozik04** [comment]
Thank you!

**Pull request merged**
