### PR TITLE
Handle out of range values on rmu data

### PR DESCRIPTION
**Pull request by elupus**
We need to apply the same out of range checks for RMU data, since these fields also send out range data on error values.

Swapping scale and offset and applying same range checks for RMU data.

### CODE REVIEW

**Comment by elupus** [comment]
Ps. I'm starting to think there are no 2's complement signed values anywhere in the pump. All are unsigned values with some defined offset to make them signed.

**Comment by yozik04** [comment]
Would be great to add some test coverage on these changes.

**Comment by elupus** [comment]
Don't seem to be able to hit the error values with the FixedPointStrange, since with positive offsets we can never hit the limit values. I've not seen any error values on the outdoor temp field so far. In theory it could indicate errors with the unused values in the gap i suppose (ie a zero value). I've removed that check for now.

**Comment by yozik04** [comment]
Great, thank you. Merged. Do you need a new release?

**Comment by elupus** [comment]
Can hold of a bit. Got a weird 32 bit degree minutes parameter issue since the myuplink upgrade that need to be looked at.

**Pull request merged**
