### PR TITLE
Detect undefined coil values for unsigned Integers

### PR DESCRIPTION
**Pull request by yozik04**

### CODE REVIEW

**Comment by yozik04** [comment]
@elupus take a look.

**Review by elupus — APPROVED** [review]
Ive not tested against pump yet, but i think this looks hood at a glance. Ill report again when ove tested on the pump.

**Comment by yozik04** [comment]
But remember it only detects it for unsigned integers. I have no idea what to do with signed as 0xffff is -1

**Comment by elupus** [comment]
I think it set it to max negative. I check for -32xxx to verify now.

**Comment by elupus** [comment]
Ie 0x8000, 0x80 and so on.

**Comment by yozik04** [comment]
Merged a PR for signed ones as well. Will need to test it.

**Comment by elupus** [comment]
Looks good. Tested for signed 16 on parameter: 41027. now that i look, i can't seem to find the unsigned error case, too many variables there, heh.

**Pull request merged**
