### PR TITLE
Pulse energy meter (BE6/BF2)

### PR DESCRIPTION
**Pull request by Andy-Voigt**

### CODE REVIEW

**Comment by Andy-Voigt** [comment]
[modbus_addresses_all_20240704-06920621343032-1.csv](https://github.com/user-attachments/files/16094686/modbus_addresses_all_20240704-06920621343032-1.csv)

**Comment by yozik04** [comment]
If you manually edited csv then this is wrong. Next time I will get a CSV from someone I will have to resolve the conflicts that the line exists in multiple places. We should keep CSV intact after export.

**Comment by Andy-Voigt** [comment]
I think we have also to set write to true and the min/max values

**Comment by yozik04** [comment]
> My csv is completely in german. This will conflict the whole file.

It is possible to change language of the unit to English before export. Then the file will be in English.

**Pull request closed without merging**
