### PR TITLE
Add Night cooling registers

### PR DESCRIPTION
**Pull request by johanschelin**
Added support for Night cooling

### CODE REVIEW

**Comment by elupus** [comment]
Can you also run the script that update the json file?

**Comment by johanschelin** [comment]
If you just tell me how - I can do it- And then I will know for future PRs as well.

Med vänlig hälsning,
Johan Schelin
________________________________
Från: Joakim Plate ***@***.***>
Skickat: Wednesday, September 13, 2023 9:11:01 PM
Till: yozik04/nibe ***@***.***>
Kopia: Johan Schelin ***@***.***>; Author ***@***.***>
Ämne: Re: [yozik04/nibe] Update s1155_s1255.csv (PR #113)


Can you also run the script that update the json file?

**Comment by yozik04** [comment]
@johanschelin Did you manually wrote these lines or you exported from the unit?
I have run our script and it failed to convert.

To update json file we have a script:
```bash
python3 -m nibe.console_scripts.convert_csv
```

**Comment by johanschelin** [comment]
I exported to CSV from the pump and then pasted the three lines. Can double check to see what could be wrong.

Has done it once before and it worked fine.

I’ll check and come back

Med vänlig hälsning,
Johan Schelin
________________________________
Från: Jevgeni Kiski ***@***.***>
Skickat: Thursday, September 14, 2023 12:48:41 PM
Till: yozik04/nibe ***@***.***>
Kopia: Johan Schelin ***@***.***>; Mention ***@***.***>
Ämne: Re: [yozik04/nibe] Update s1155_s1255.csv (PR #113)


@johanschelin<https://github.com/johanschelin> Did you manually wrote these lines or you exported from the unit?
I have run our script and it failed to convert.

To update json file we have a script:

python3 -m nibe.console_scripts.convert_csv

**Comment by johanschelin** [comment]
Found a tab in the row directly above that probably got affected when I pasted the new rows. Have added that to the PR. Can you see if the script for json-conversion works now?
Tried to run the conversion tool myself but obviously lack some knowledge – succeeded almost – but get a bunch of errors when converting.

**Comment by yozik04** [comment]
@johanschelin Thank you!

**Comment by johanschelin** [comment]
Will you create a PR for this to be pulled into the core for 2023.10?

**Comment by elupus** [comment]
I will when i get a chance. Feel free to do it if you have the time.

**Comment by johanschelin** [comment]
I am learning but not completely sure of the process for merging to core, do YOU need to make a new release of the master branch first, before I can create a PR from that one?



________________________________
Från: Joakim Plate ***@***.***>
Skickat: den 30 september 2023 13:47
Till: yozik04/nibe ***@***.***>
Kopia: Johan Schelin ***@***.***>; Mention ***@***.***>
Ämne: Re: [yozik04/nibe] Add Night cooling registers (PR #113)


I will when i get a chance. Feel free to do it if you have the time.

**Comment by yozik04** [comment]
I have released 2.4.0 to PyPi. So we need to bump version in HA core.

**Pull request merged**
