### PR TITLE
Support parsing 32 bit values log set

### PR DESCRIPTION
**Pull request by elupus**
The log set data for 32 bit values seem to come with a "virtual" address at the next index from the data. So re-combine the data at reception.

### CODE REVIEW

**Comment by elupus** [comment]
I don't yet have a full raw log of data on this. So not fully tested yet. Do you happen to have one @yozik04 when you looked at this for mqtt branch?

**Comment by yozik04** [comment]
I intentionally changed to pick only 16bit parameters on my heat pump. I do not have a log for that.

**Comment by elupus** [comment]
Feeling quite confident this should be alright. Found a user log at https://github.com/home-assistant/core/issues/84497 and added case for that. The parsed value looks quite alright. The number of compressor starts somewhat high, perhaps the accumulated kwh too high, but i think that value might have wrong scaling in the database.

**Comment by yozik04** [comment]
I verified it. Seems to be correct.

**Pull request merged**
