### PR TITLE
Attempt to fixup data conversion for modbus

### LINKED ISSUE #53: Modbus write using wrong encoding
Extracted from #50 

We are seemingly not providing the write command with an array of int16 values.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/nibe_heatpump/init.py:224
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:06:09 AM (3 occurrences)
Last logged: 12:07:07 AM

[1657699968] The value contained in the request data field is not an allowable value for the server.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/umodbus/functions.py", line 1515, in values
struct.pack(">" + conf.MULTI_BIT_VALUE_FORMAT_CHARACTER, value)
struct.error: required argument is not an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/number/init.py", line 109, in async_set_value
await entity.async_set_native_value(native_value)
File "/config/custom_components/nibe_heatpump/number.py", line 68, in async_set_native_value
await self._async_write_coil(value)
File "/config/custom_components/nibe_heatpump/init.py", line 304, in _async_write_coil
await self.coordinator.async_write_coil(self._coil, value)
File "/config/custom_components/nibe_heatpump/init.py", line 224, in async_write_coil
coil = await self.connection.write_coil(coil)
File "/usr/local/lib/python3.10/site-packages/nibe/connection/modbus.py", line 110, in write_coil
result = await self._client.write_registers(
File "/usr/local/lib/python3.10/site-packages/async_modbus/core.py", line 233, in write_registers
request = self.protocol.write_multiple_registers(
File "/usr/local/lib/python3.10/site-packages/umodbus/client/tcp.py", line 221, in write_multiple_registers
function.values = values
File "/usr/local/lib/python3.10/site-packages/umodbus/functions.py", line 1517, in values
raise IllegalDataValueError
umodbus.exceptions.IllegalDataValueError: The value contained in the request data field is not an allowable value
for the server.
```

### PR DESCRIPTION
**Pull request by elupus**
Attempt to fix #53

### CODE REVIEW

**Comment by yozik04** [comment]
Looks good to me... I can merge if it is ready.

**Comment by elupus** [comment]
Lets give it a try

**Comment by yozik04** [comment]
Do I understand it right that you can not let people test it until I release a new version?

**Comment by elupus** [comment]
For testing in HA yes. If we had a cli in place we could test using that i suppose by just pip installing master.

**Comment by dkmh** [comment]
Change gives me this error:

Unexpected error fetching Nibe Heat Pump data: 'numpy.uint16' object has no attribute 'to_bytes'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/nibe_heatpump/__init__.py", line 237, in _async_update_data
    return await self._async_update_data_internal()
  File "/config/custom_components/nibe_heatpump/__init__.py", line 260, in _async_update_data_internal
    async for coil in self.connection.read_coils(_get_coils()):
  File "/usr/local/lib/python3.10/site-packages/nibe/connection/__init__.py", line 26, in read_coils
    yield await self.read_coil(coil, timeout)
  File "/usr/local/lib/python3.10/site-packages/nibe/connection/modbus.py", line 110, in read_coil
    coil.value = self.coil_encoder.decode(coil, encode_u16_list(result))
  File "/usr/local/lib/python3.10/site-packages/nibe/connection/modbus.py", line 45, in encode_u16_list
    return bytes(
  File "/usr/local/lib/python3.10/site-packages/nibe/connection/modbus.py", line 46, in <genexpr>
    byte for val in data for byte in val.to_bytes(2, "little", signed=False)
AttributeError: 'numpy.uint16' object has no attribute 'to_bytes'

**Comment by elupus** [comment]
What the heck. How is that not caught by the tests.

**Comment by elupus** [comment]
Ah. Its returned from umodbus. Need an int cast before to_bytes()

**Pull request merged**
