### PR TITLE
Don't print debug errors for request packets

### PR DESCRIPTION
**Pull request by elupus**

### CODE REVIEW

**Comment by yozik04** [comment]
But how these packets can end up there? I am voting against that. It might hide an another problem, like running multiple nibegw instances or using multicast?

**Comment by elupus** [comment]
Nibepi need to see the requests. I've modified this in the esp32 version of the gateway to forward those packets too. They are not hidden really just no error message in debug logs. You still see the packet.

**Comment by yozik04** [comment]
I do not understand why nibepi needs to see these requests?

**Comment by elupus** [comment]
I dont think it need them per say, but it is expecting them and wont work properly without them.

**Comment by elupus** [comment]
Ps. From a debugging perspective, its also nice to see them. Ive also modified the esp32 version to even send packets with bad data. So you can debug issues on the remote side rather then the gateway side

**Comment by yozik04** [comment]
But I released 0.5.0 already today. So this PR will not get into that version.

**Pull request merged**
